version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-analytic
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - main-nt
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: be-analytic-database
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - main-nt
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  minio:
    image: minio
volumes:
  pg_data: { }
networks:
  main-nt: { }