"""created deals leads table

Revision ID: 21eecd5b62b5
Revises: df6b0e4a926d
Create Date: 2025-05-29 15:55:15.160471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21eecd5b62b5'
down_revision: Union[str, None] = 'df6b0e4a926d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'ATTEMPTING_CONTACT', 'CONTACTED', 'ENGAGED', 'QUALIFIED', 'NOT_INTERESTED', 'UNQUALIFIED', 'BAD_CONTACT_INFO', 'NO_RESPONSE', 'CONVERTED', name='lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('stage', postgresql.ENUM('QUALIFICATION', 'NEEDS_ANALYSIS', 'PROPOSAL_SENT', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='deal_stage'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('company_branches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_branches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('deals')
    op.drop_table('leads')
    # ### end Alembic commands ###
