"""company some fields was optional

Revision ID: 2de8b9d30c57
Revises: 2d7dc8a78de4
Create Date: 2025-05-09 21:30:22.560288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de8b9d30c57'
down_revision: Union[str, None] = '2d7dc8a78de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'company_logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'company_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'company_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'company_logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
