"""companies altered table

Revision ID: 30cb65bba67a
Revises: 45422b3962bd
Create Date: 2025-05-12 09:52:11.754921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30cb65bba67a'
down_revision: Union[str, None] = '45422b3962bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'business_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_activity', postgresql.ENUM('PHYSICAL_COMPANY', 'DIGITAL_COMPANY', name='businessactivityenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
