"""branches: removed postal code

Revision ID: 45422b3962bd
Revises: 2de8b9d30c57
Create Date: 2025-05-11 22:38:47.705786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45422b3962bd'
down_revision: Union[str, None] = '2de8b9d30c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_branches', 'postal_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_branches', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
