"""
employee changed roles management

Revision ID: 5f36a7a93a0e
Revises: b77247f20789
Create Date: 2025-06-03 05:35:41.510554

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f36a7a93a0e'
down_revision: Union[str, None] = 'b77247f20789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_branches', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.add_column('employees', sa.Column('is_owner', sa.Boolean(), default=False, nullable=True))
    op.add_column('employees', sa.Column('is_manager', sa.Boolean(), default=False, nullable=True))
    op.alter_column('employees', 'role',
                    existing_type=postgresql.ENUM('OWNER', 'EMPLOYEE', name='employee_role'),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'role',
                    existing_type=sa.String(),
                    type_=postgresql.ENUM('OWNER', 'EMPLOYEE', name='employee_role'),
                    existing_nullable=False)
    op.drop_column('employees', 'is_manager')
    op.drop_column('employees', 'is_owner')
    op.alter_column('company_branches', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
