"""leads added company id

Revision ID: b77247f20789
Revises: 21eecd5b62b5
Create Date: 2025-05-31 23:33:33.502764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77247f20789'
down_revision: Union[str, None] = '21eecd5b62b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_branches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('deals', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deals', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'company_id')
    op.alter_column('company_branches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
