"""created companies + branch models

Revision ID: ce797bc1d594
Revises: ba0fcdb424e0
Create Date: 2025-05-09 14:30:22.398762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce797bc1d594'
down_revision: Union[str, None] = 'ba0fcdb424e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_logo', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.Enum('SOLE_PROPRIETORSHIP', 'JOIN_STOCK_COMPANY', 'LIMITED_LIABILITY_COMPANY', name='businesstypeenum'), nullable=False),
    sa.Column('business_activity', sa.Enum('PHYSICAL_COMPANY', 'DIGITAL_COMPANY', name='businessactivityenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('company_website', sa.String(), nullable=True),
    sa.Column('company_phone_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_table('company_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_branches')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
